logging.level:
  slanzini: DEBUG
spring:
  profiles:
    active: local
server:
  servlet.context-path: /zk-demo
  port: 8280
scheduled-task:
  users-elaboration: "0 */1 * * * *"
user-api:
  base-path: localhost:8886/hello-test
zk:
  url: "localhost:2181"
  session-timeout: 3000
  connection-timeout: 3000